services: # this has a source and destination database and the elt script
  source_postgres: 
    image: postgres:10
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  destination_postgres: 
      image: postgres:10
      ports:
        - "5434:5432"
      networks:
        - elt_network
      environment:
        POSTGRES_DB: destination_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secret
  
  elt_script:
    build:
      context: ./elt
      dockerfile: Dockerfile
    command: ["python", "elt.py"]
    networks:
      - elt_network
    depends_on: # this ensures the script only runs if both databases are up
      - source_postgres
      - destination_postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    command:
      [
        "run",  # command to run the models on top of data
        "--profiles-dir",  
        "/root",
        "--project-dir",
        "/dbt"
      ]
    networks:
      - elt_network
    volumes:
      - ./custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      - elt_script
    environment:
      DBT_PROFILE: custom_postgres
      DBT_TARGET: dev
      
networks:
  elt_network:
    driver: bridge